# Generated by Django 4.2 on 2023-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_city_country_alter_country_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continent_img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.TextField(),
        ),
    ]
