# Generated by Django 4.2 on 2023-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_continent_continent_img_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continent_img',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.TextField(blank=True),
        ),
    ]
