# Generated by Django 4.2 on 2023-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_city_country_alter_country_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateweather',
            name='status_icon',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
